# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: New issue
on:
  issues:
    types:
      - opened
jobs:
  add-comment:
    runs-on: ubuntu-latest
    needs: add-index-record
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "This went to the index and has an object id of ${{ needs.add-index-record.outputs.object_id }}"
  add-index-record:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add to index
        uses: ./.github/actions/add-index-record
        with:
          app_id: ${{ secrets.ALGOLIA_APP_ID }}
          api_key: ${{ secrets.ALGOLIA_API_KEY }}
          index_name: ${{ github.event.repository.name }}
          record: |
            {"title": "${{ github.event.issue.title }}", "url": "${{ github.event.issue.html_url }}", "labels": "${{ github.event.issue.labels }}",
             "objectID": "${{ github.event.issue.number }}"}
